services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_REACT_APP_FIREBASE_API_KEY: ${VITE_REACT_APP_FIREBASE_API_KEY}
        VITE_REACT_APP_FIREBASE_AUTH_DOMAIN: ${VITE_REACT_APP_FIREBASE_AUTH_DOMAIN}
        VITE_REACT_APP_FIREBASE_PROJECT_ID: ${VITE_REACT_APP_FIREBASE_PROJECT_ID}
        VITE_REACT_APP_FIREBASE_STORAGE_BUCKET: ${VITE_REACT_APP_FIREBASE_STORAGE_BUCKET}
        VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
        VITE_REACT_APP_FIREBASE_APP_ID: ${VITE_REACT_APP_FIREBASE_APP_ID}
        VITE_REACT_APP_FIREBASE_APP_CHECK_SITE_KEY: ${VITE_REACT_APP_FIREBASE_APP_CHECK_SITE_KEY}
    image: wedding-react:latest
    ports:
      - '80:80'
    read_only: true
    tmpfs:
      - /run:rw,mode=1777 # keep /run writable for nginx.pid
      - /tmp:rw,mode=1777
      - /var/cache/nginx:rw,mode=1777
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:8080/healthz']
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    env_file: .env
